name: "Azure DevOps Github Integration"
description: "Automatically links a GitHub PR to Azure DevOps Work Item and/or set a custom state for it"
author: "Mukul Garg"
branding:
  icon: "check"
  color: "green"
inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  devops-work-item-regex:
    description: "Regex which gets applied to title and body (in this order) to find the DevOpsId (only first match gets used)"
    required: true
  set-to-state:
    description: "The state you want the work item to be set to (exact string match). Keep empty to skip."
    required: false
  dont-set-state-while-prs-open:
    description: "Set to true if you don't want to set the state while GitHub PRs associated with the DevOps Work Item are still open"
    required: false
  add-pr-link:
    description: "Set to true if you want to set the url of the PR on the work item"
    required: false
  devops-organization:
    description: "The url-slug of the devops organization"
    required: false
  devops-pat:
    description:
      "The Personal-Access-Token (PAT) to authorize the action to communicate with DevOps.
      As of now the PAT needs the following rights:
      - 'Work Items - Read, write, & manage' to move the work item between states
      - 'Full Access' to link the PR to the work item (currently there is no specific right to
      only allow this, it only works with full access. Be careful who you give this token!)"
    required: true
  fail-on-error:
    description:
      "If you don't want the action to fail (and create failed checks) on error (e.g. when
      # the work item id couldn't be found via the regex or an unforseen error occurs) set
      # this to false. Setting this to false will also allow partial completion (e.g. only
      # link pr but not move the state)"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
