name: "Build and Push"
on:
  push: 
    branches:
      - main    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - name: NPM iunstall
      run: npm install
    - name: NPM run all
      run: npm run all
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[mukulgit123 infrastructure] Build"
        commit_user_name: mukulgit123 infrastructure
        commit_user_email: infrastructure@mukulgit123.ag
        commit_author: mukulgit123 infrastructure <infrastructure@mukulgit123.ag>
